### ISSUE TITLE
When header error is found (for example, header missing) there is no LOG error in the pep LOG

### ISSUE THREAD

**Issue by jcalderin** [telefonicaid/fiware-orion-pep#170]
This is the response, but in the log there is nothing:

```
{
  "message": "Some headers were missing from the request: [\"x-auth-token\"]"
}

```

Effort: 1 man day

**Comment by dmoranj** [comment]
This is intentional. Errors returned to the user are not errors from the point of view of the PEP: the clearest example is a 403 forbidden error.  Tracing all the errors returned from the PEP would be really consuming, and they really don't add information from the component point of view (I'm not sure they will give more information than the one you are getting in the response).

**Comment by dmoranj** [comment]
NTC
